Repository DhanushNehru/calculator, pull requests merged in 2022-10, with the labels that each got.

#6 Add event listeners on numbers
  script.js
Labels: enhancement, hacktoberfest

#7 Add key listeners for operators and different keys
  script.js
Labels: enhancement, hacktoberfest

#9 Added a new operation i.e. to calculate exponential(e^x)
  index.html
  script.js
  style.css
Labels: hacktoberfest

#18 Responsive UI and known JS bug fix
  README.md
  index.html
  script.js
  style.css
Labels: enhancement, hacktoberfest

#30 enhanced aligned the C button with other buttons
  index.html
  style.css
Labels: bug, good first issue, hacktoberfest

#35 Responsive 2.0 UI fixed
  index.html
  script.js
  style.css
Labels: enhancement, hacktoberfest

#49 sound effect
  index.html
  script.js
  tink.wav
Labels: enhancement, hacktoberfest

#50 changed text of more functions button to hide functions when clicked
  script.js
Labels: enhancement, hacktoberfest

#51 Added neumorphism effect
  style.css
Labels: enhancement, hacktoberfest

#55 Features escape button
  index.html
  script.js
Labels: enhancement, hacktoberfest

#68 history functionality added
  index.html
  script.js
  style.css
Labels: enhancement, hacktoberfest

#73 Created Contributors.md
  Contributors.md
Labels: documentation, good first issue, hacktoberfest

#74 Add dark-mode and neon-theme.
  index.html
  logos/brightness.png
  logos/neon.png
  logos/night-mode.png
  style.css
Labels: enhancement, hacktoberfest

#75 0 will be shown default on screen
  script.js
Labels: good first issue, hacktoberfest

#82 Added inverse trigonometric sin tan and cos
  index.html
  script.js
Labels: hacktoberfest
